### ISSUE TITLE
laravel-scout-elasticsearch v3.0.0 不能用

### ISSUE THREAD

**Issue by dengqihua** [baijunyao/laravel-scout-elasticsearch#3]
安装版本和依赖如下：
![image](https://user-images.githubusercontent.com/7666239/65477634-7da82b80-deb9-11e9-9623-3ace85461902.png)

然后使用的时候报错：
![image](https://user-images.githubusercontent.com/7666239/65477667-987aa000-deb9-11e9-8dee-1f71507588bf.png)

**Comment by baijunyao** [comment]
多谢反馈；我先修复了兼容性的问题； 后续抽时间测试各个功能；

**Comment by dengqihua** [comment]
多谢回复，辛苦辛苦！

发自我的iPhone
