### ISSUE TITLE
按照文档弄的报错

### ISSUE THREAD

**Issue by XinJiangQingMang** [baijunyao/laravel-scout-elasticsearch#6]
```
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [laravel_hbh_202004166887]","resource.type":"index_or_alias","resource.id":"laravel_hbh_202004166887","index_uuid":"_na_","index":"laravel_hbh_202004166887"}],"type":"index_not_found_exception","reason":"no such index [laravel_hbh_202004166887]","resource.type":"index_or_alias","resource.id":"laravel_hbh_202004166887","index_uuid":"_na_","index":"laravel_hbh_202004166887"},"status":404}
http://big.com/search?s=%2F%2Fsearch
```

es  最新版 用的

**Comment by XinJiangQingMang** [comment]
或者有要求 es 版本  laravel 版本吗  laravel 7+

**Comment by XinJiangQingMang** [comment]
{
  "name" : "DESKTOP-MR01251",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "E-ds3tyrSAiiuJGoIfaVQA",
  "version" : {
    "number" : "7.6.2",
    "build_flavor" : "default",
    "build_type" : "zip",
    "build_hash" : "ef48eb35cf30adf4db14086e8aabd07ef6fb113f",
    "build_date" : "2020-03-26T06:34:37.794943Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

**Comment by baijunyao** [comment]
有执行 `php artisan scout:import "App\Models\xxx"` 命令生成索引吗？

**Comment by XinJiangQingMang** [comment]
> 有执行 `php artisan scout:import "App\Models\xxx"` 命令生成索引吗？

执行了 
![image](https://user-images.githubusercontent.com/19700237/79861570-32320d80-8407-11ea-83c0-3d1e4620ee98.png)

**Comment by XinJiangQingMang** [comment]
执行了 
![image](https://user-images.githubusercontent.com/19700237/79861638-48d86480-8407-11ea-9594-9c157f94c13c.png)
@baijunyao

**Comment by baijunyao** [comment]
我刚用 Elasticsearch 7.6.2 版本没有复现报错； 你可以试试我的 Docker image [https://hub.docker.com/repository/docker/baijunyao/elasticsearch](https://hub.docker.com/repository/docker/baijunyao/elasticsearch) 

另外生成索引的时候需要用到 数据表 名；  
建议使用跟数据表名一致的 Model 命名；  
可以使用 `curl '127.0.0.1:9200/_cat/indices'` 查看 索引；  
对比报错的索引追下看有什么问题；

**Comment by XinJiangQingMang** [comment]
索引是不是空表建最好 如果表里有几万条数据呢  构建特别慢

**Comment by XinJiangQingMang** [comment]
我在linux 下部署了es  这次不存在这个问题了 表名一致 搜索很快
